
// Auto-generated by AutoPilot on 29-07-2023 at 00:01:43

const express = require('express');
const router = express.Router();

// route to give a random fact about Coldplay
router.get('/giveMeFacts', (req, res) => {
    // array of facts
    const facts = [
        'Coldplay has been nominated for a total of 91 awards, out of which they have won 48.',
        'The lead vocalist and songwriter of Coldplay, Chris Martin, is the ex-husband of Hollywood actress Gwyneth Paltrow.',
        'Coldplay has sold over 100 million records worldwide, making them one of the world’s best-selling music artists.',
        'The band’s first full-length album, Parachutes, was released in 2000 and sold over 8 million copies worldwide.'
    ];

    // generate a random index between 0 to 3
    const index = Math.floor(Math.random() * 4);

    // return the fact at the generated index
    res.send(facts[index]);
});

module.exports = router;